version: '3.0'

services:
  # consul server，对外暴露的ui接口为8500，只有在2台consul服务器的情况下集群才起作用
  consulserver:
    image: consul:latest
    hostname: consulserver
    ports:
      - '8300'
      - '8400'
      - '8500:8500'
      - '53'
    command: [agent, -server, -ui, -client=0.0.0.0, -bootstrap-expect=1]
    volumes:
      - ../volumes/consul4/data:/consul/data
      - ../volumes/consul4/log:/consul/log
      - ../volumes/consul4/consul-client.json:/consul/config/consul.json
    networks:
      - app
networks:
  app:
